Class {
	#name : #FamixJavaInheritanceParametric,
	#superclass : #FamixJavaEntity,
	#traits : 'FamixTInheritanceParametric',
	#classTraits : 'FamixTInheritanceParametric classTrait',
	#category : #'Famix-Java-Entities-Entities'
}

{ #category : #meta }
FamixJavaInheritanceParametric class >> annotation [

	<FMClass: #InheritanceParametric super: #FamixJavaEntity>
	<package: #'Famix-Java-Entities'>
	<generated>
	^ self
]
