Class {
	#name : #FamixJavaParametricInheritance,
	#superclass : #FamixJavaEntity,
	#traits : 'FamixTParametricInheritance',
	#classTraits : 'FamixTParametricInheritance classTrait',
	#category : #'Famix-Java-Entities-Entities'
}

{ #category : #meta }
FamixJavaParametricInheritance class >> annotation [

	<FMClass: #ParametricInheritance super: #FamixJavaEntity>
	<package: #'Famix-Java-Entities'>
	<generated>
	^ self
]
